image: golang:1.12

stages:
  - test

env:
  - GO111MODULE=on

before_script:
  - go get -u golang.org/x/lint/golint
  - go get -u github.com/golang/dep/cmd/dep
  - cp -r $CI_PROJECT_DIR /go/src/
  - cd /go/src/aos_common/
  - cp ci/rootCA.crt.pem  /etc/ssl/certs/

test:
  stage: test
  script:
    - export
    - echo "==== Run lint ===="
    - ci/lint.sh
    - echo "==== Run unit tests with coverage ===="
    - go test  $(go list ./... | grep -v "/visprotocol") -v -coverprofile .testCoverage.txt
    - go tool cover -func=.testCoverage.txt
